# -*- coding: utf-8 -*-
"""srp metacogintive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u61O1QxpzPJ48x5hUucOSOxkPwrLYfth
"""

import zipfile, os

!pip install transformers torch accelerate -q

import zipfile, os

with zipfile.ZipFile("ipseitas_gap_learner_package.zip", "r") as z:
  z.extractall(".")

os.chdir("ipseitas_gap_learner")

from ipseitas_pipeline import IpseitasGapLearner, HuggingFaceLLM

norm = """
Understand why particles can behave like waves and how this relates to the double-slit experiment.
"""

provider = HuggingFaceLLM(model_name="Qwen/Qwen2.5-1.5B-Instruct")
learner = IpseitasGapLearner(provider=provider)

learner.run(norm_of_study=norm, steps=3)

report = learner.report_markdown(norm)
print(report)